# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write    

    steps:
      - uses: actions/checkout@v3

      - name: Install .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install Azure Functions SDK
        run: npm install -g azure-functions-core-tools@4
      - name: Install Dapr SDK
        run: wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --logger trx

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          job_summary: true
          files: |
            **/*.trx
